source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'devise', "~> 2.1.2"
gem 'mongoid', "~> 3.0.14"
gem 'mongoid_spacial', "~> 0.2.13"
gem 'haml', '~> 3.1.2'
gem "haml-rails", "~> 0.3.5"
gem 'bson_ext', '~> 1.7.1'
gem 'rails-backbone', "~> 0.8.0"
gem 'skeleton-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
   gem 'cucumber-rails'
   gem "email_spec"
	gem 'rspec-rails', '~> 2.12.0'
	gem 'mongoid-rspec', '~> 1.5.4'
	gem 'capybara', '~> 2.0.1'
	gem 'factory_girl_rails', '~> 4.1.0'
	gem 'database_cleaner', '~> 0.9.1'
	gem 'jasmine', '~> 1.2.1'
end
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
