source 'https://rubygems.org'

gem 'bcrypt-ruby', '3.0.1'
gem 'bootstrap-sass', '2.0.0'
gem 'bootstrap-will_paginate', '0.0.6'
gem 'builder',  '>= 3.0.0'
gem 'faker', '1.0.1'
gem 'i18n', '>= 0.6.0'
gem 'jquery-rails', '2.0.2'
gem 'nokogiri', '>= 1.5.0'
gem 'rails', '>= 3.2.12'
gem 'rb-readline'
gem 'thin'
gem 'will_paginate', '3.0.3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '3.2.2'
  gem 'sass-rails',   '3.2.4'  
  gem 'uglifier', '1.2.3'
end

group :development do  
  gem 'annotate',     '>= 2.4.1.beta'
  #gem "therubyracer", '>= 0.11.0beta8'
  #gem 'libv8', '~> 3.11.8'
end

group :development, :test do  
  gem 'guard'
  #gem 'guard-rspec', '0.5.5' 
  gem 'guard-spork', '1.2.0'  
  #gem 'rspec-rails', '2.10.0' 
  gem 'spork', '0.9.2'
  gem 'sqlite3', '1.3.6'
  gem 'win32console'
  gem 'wdm', '~> 0.0.3'
end

group :production do
  gem 'pg', '0.12.2'
end

group :test do
  gem 'autotest-rails' # if you're using rails
  gem 'capybara', '1.1.2'
  gem 'cucumber-rails', '1.3.1', :require => false
  gem 'database_cleaner', '0.7.0'  
  gem 'factory_girl_rails', '4.1.0'
  gem 'gherkin', '<= 2.11.6'
  gem 'growl', '1.0.3'
  gem 'guard-rspec', '1.2.1' 
  #gem 'guard-spork', '0.3.2' 
  gem 'launchy', '2.1.0'  
  gem 'rb-fchange', :require => false
  gem 'rb-fsevent', '0.9.1', :require => false
  gem 'rb-notifu', '0.0.4'
  #gem 'rb-inotify', :require => false
  gem 'rspec', '2.11.0'
  gem 'rspec-rails', '2.11.0' 
  #gem 'spork', '0.9.0'
  gem 'wdm', '~> 0.0.3'
  gem 'ZenTest', "~> 4.4.2"
end

