# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526c2b7f1f28494feaf397d4d98f90d27cbcc704698b1e6bb99ce9a4be69f0eb93000954d10767e08cb1b6edbaddbea6bae91227ab5a8cdb0b5ca28616a81067

test:
  secret_key_base: 1b059974e7afdede3b1ae0d6b8d2b706c195484b77de6473a1b8a90ae9940bbf1bffb126659a2d4052d912c3c85fb6d0e02960780a0994b10eff912adde44f98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
